<?php

return [
    'roles' => [
        'super_admin' => [
            'label' => 'Super Admin',
            'system' => true,
            'permissions' => '*',
        ],
        'admin' => [
            'label' => 'Admin',
            'system' => true,
            'permissions' => [
                'users.view',
                'users.view_all',
                'users.create',
                'users.update',
                'users.disable',
                'users.assign_roles',
                'roles.view',
                'roles.manage',
                'permissions.view',
                'departments.view',
                'departments.view_all',
                'departments.create',
                'departments.update',
                'departments.delete',
                'departments.manage_members',
                'files.department.view_all',
                'files.department.manage_all',
                'files.department.view_descendants',
                'files.department.manage_assigned',
                'files.department.manage_descendants',
                'files.folder.view',
                'files.folder.create',
                'files.folder.rename',
                'files.folder.delete',
                'files.file.view',
                'files.file.upload',
                'files.file.rename',
                'files.file.download',
            ],
        ],
        'administrator_user' => [
            'label' => 'Administrator User',
            'system' => true,
            'permissions' => [
                'files.department.view_descendants',
                'files.department.manage_descendants',
                'files.folder.view',
                'files.folder.create',
                'files.folder.rename',
                'files.folder.delete',
                'files.file.view',
                'files.file.upload',
                'files.file.rename',
                'files.file.download',
            ],
        ],
        'member' => [
            'label' => 'Employee',
            'system' => true,
            'permissions' => [
                'files.department.manage_assigned',
                'files.folder.view',
                'files.folder.create',
                'files.folder.rename',
                'files.folder.delete',
                'files.file.view',
                'files.file.upload',
                'files.file.rename',
                'files.file.download',
            ],
        ],
    ],

    'permissions' => [
        'users.view' => 'View users within the actor department scope.',
        'users.view_all' => 'View users across all departments.',
        'users.create' => 'Create users.',
        'users.update' => 'Update users.',
        'users.disable' => 'Disable or reactivate users.',
        'users.assign_roles' => 'Assign roles to users.',
        'roles.view' => 'View roles.',
        'roles.manage' => 'Manage role definitions and assignments.',
        'permissions.view' => 'View the permission catalog.',
        'departments.view' => 'View departments within the actor department scope.',
        'departments.view_all' => 'View all departments regardless of membership.',
        'departments.create' => 'Create departments.',
        'departments.update' => 'Update departments.',
        'departments.delete' => 'Delete empty departments.',
        'departments.manage_members' => 'Manage department membership.',
        'files.department.view_all' => 'View all department file spaces regardless of membership.',
        'files.department.manage_all' => 'Manage all department file spaces regardless of membership.',
        'files.department.view_descendants' => 'View assigned department file spaces and their active descendants.',
        'files.department.manage_assigned' => 'Manage directly assigned active department file spaces.',
        'files.department.manage_descendants' => 'Manage assigned active department file spaces and their active descendants.',
        'files.folder.view' => 'Open folders inside an authorized file space.',
        'files.folder.create' => 'Create folders inside an authorized manageable file space.',
        'files.folder.rename' => 'Rename folders inside an authorized manageable file space.',
        'files.folder.delete' => 'Move folders to trash inside an authorized manageable file space.',
        'files.file.view' => 'Open file entries inside an authorized file space.',
        'files.file.upload' => 'Upload files into an authorized manageable file space.',
        'files.file.rename' => 'Rename files inside an authorized manageable file space.',
        'files.file.download' => 'Download file content from an authorized file space.',
        'system.manage' => 'Perform protected system administration operations.',
    ],
];
