<?php

namespace App\Support\Api;

enum ApiErrorCode: string
{
    case AUTH_REQUIRED = 'AUTH_REQUIRED';
    case INVALID_CREDENTIALS = 'INVALID_CREDENTIALS';
    case USER_DISABLED = 'USER_DISABLED';
    case ACCESS_DENIED = 'ACCESS_DENIED';
    case VALIDATION_FAILED = 'VALIDATION_FAILED';
    case UPLOAD_TOO_LARGE = 'UPLOAD_TOO_LARGE';
    case STORAGE_QUOTA_EXCEEDED = 'STORAGE_QUOTA_EXCEEDED';
    case FILE_CONTENT_UNAVAILABLE = 'FILE_CONTENT_UNAVAILABLE';
    case PERMANENT_PURGE_FAILED = 'PERMANENT_PURGE_FAILED';
    case RESOURCE_CONFLICT = 'RESOURCE_CONFLICT';
    case RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND';
    case PUBLIC_SHARE_NOT_FOUND = 'PUBLIC_SHARE_NOT_FOUND';
    case PUBLIC_SHARE_PASSWORD_REQUIRED = 'PUBLIC_SHARE_PASSWORD_REQUIRED';
    case PUBLIC_SHARE_PASSWORD_INVALID = 'PUBLIC_SHARE_PASSWORD_INVALID';
    case RESOURCE_PASSWORD_REQUIRED = 'RESOURCE_PASSWORD_REQUIRED';
    case RESOURCE_PASSWORD_INVALID = 'RESOURCE_PASSWORD_INVALID';
    case TOO_MANY_RESOURCE_PASSWORD_ATTEMPTS = 'TOO_MANY_RESOURCE_PASSWORD_ATTEMPTS';
    case TOO_MANY_PUBLIC_SHARE_ATTEMPTS = 'TOO_MANY_PUBLIC_SHARE_ATTEMPTS';
    case SESSION_EXPIRED = 'SESSION_EXPIRED';
    case TOO_MANY_LOGIN_ATTEMPTS = 'TOO_MANY_LOGIN_ATTEMPTS';
}
